spring:
  application:
    name: shortener-mvc

  #----------Virtual threads----------
  threads:
    virtual:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/shortener
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
  data:
    redis:
      client-type: lettuce
      connection:
        host: localhost
        port: 6379
  cache:
    type: redis
    redis:
      key-prefix: shortener
      use-key-prefix: true
      cache-null-values: false
      enable-statistics: false
      time-to-live: PT1H # 1 hour, consider P7D - 7 days

server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    enable:
      tomcat: true
  prometheus:
    metrics:
      export:
        enabled: true
  observations:
    annotations:
      enabled: true

logging:
  level:
    com.shortener.shortenermvc: DEBUG  # Custom package logging
    org.springframework: WARN
    org.springframework.security: WARN
    org.hibernate: WARN


